site_name: Visualización geoespacial
pages:
    - Hello: index.md
    - Sesión 1: s1/sesion1.md
    - Sesión 2: s2/sesion2.md
    - Sesión 3: s3/sesion3.md
    - Sesión 4: s4/sesion4.md
theme: material